export const SORT_BY_PAIRS = [
  {
    label: 'Name',
    value: 'name'
  },
  {
    label: 'Main',
    value: 'main'
  },
  {
    label: 'Extended',
    value: 'mainp'
  },
  {
    label: 'Completionist',
    value: 'comp'
  },
  {
    label: 'Average Time',
    value: 'averagea'
  },
  {
    label: 'Top Rated',
    value: 'rating'
  },
  {
    label: 'Most Popular',
    value: 'popular'
  },
  {
    label: 'Most Backlogs',
    value: 'backlog'
  },
  {
    label: 'Most Submissiones',
    value: 'usersp'
  },
  {
    label: 'Most Played',
    value: 'playing'
  },
  {
    label: 'Most Speedruns',
    value: 'speedrun'
  },
  {
    label: 'Release Date',
    value: 'release'
  }
]

export const PLATFORM_VALUES = [
  '3DO',
  'Acorn Archimedes',
  'Amiga',
  'Amiga CD32',
  'Amstrad CPC',
  'Android',
  'Apple II',
  'Arcade',
  'Atari 8-bit Family',
  'Atari 2600',
  'Atari 5200',
  'Atari 7800',
  'Atari Jaguar',
  'Atari Jaguar CD',
  'Atari Lynx',
  'Atari ST',
  'BBC Micro',
  'Browser',
  'ColecoVision',
  'Commodore 64',
  'Commodore PET',
  'Commodore VIC-20',
  'Dreamcast',
  'Emulated',
  'FM Towns',
  'Game & Watch',
  'Game Boy',
  'Game Boy Advance',
  'Game Boy Color',
  'Gear VR',
  'Gizmondo',
  'Google Stadia',
  'Intellivision',
  'Interactive Movie',
  'iOS',
  'Linux',
  'Mac',
  'Mobile',
  'MSX',
  'N-Gage',
  'NEC PC-88',
  'NEC PC-98',
  'NEC PC-FX',
  'Neo Geo',
  'Neo Geo CD',
  'Neo Geo Pocket',
  'NES',
  'Nintendo 3DS',
  'Nintendo 64',
  'Nintendo DS',
  'Nintendo GameCube',
  'Nintendo Switch',
  'Oculus Go',
  'Oculus Quest',
  'Odyssey',
  'Odyssey 2',
  'OnLive',
  'Ouya',
  'PC',
  'PC VR',
  'Philips CD-i',
  'PlayStation',
  'PlayStation 2',
  'PlayStation 3',
  'PlayStation 4',
  'PlayStation 5',
  'PlayStation Mobile',
  'PlayStation Now',
  'PlayStation Portable',
  'PlayStation Vita',
  'PlayStation VR',
  'Plug & Play',
  'Sega 32X',
  'Sega CD',
  'Sega Game Gear',
  'Sega Master System',
  'Sega Mega Drive/Genesis',
  'Sega Pico',
  'Sega Saturn',
  'SG-1000',
  'Sharp X1',
  'Sharp X68000',
  'Super Nintendo',
  'Tiger Handheld',
  'TurboGrafx-16',
  'TurboGrafx-CD',
  'Virtual Boy',
  'Wii',
  'Wii U',
  'Windows Phone',
  'WonderSwan',
  'Xbox',
  'Xbox 360',
  'Xbox One',
  'Xbox Series X/S',
  'Zeebo',
  'ZX Spectrum'
]

export const GENRE_VALUES = [
  'Action',
  'Adventure',
  'Arcade',
  'Battle Arena',
  "Beat 'em Up",
  'Board Game',
  'Breakout',
  'Card Game',
  'City-Building',
  'Compilation',
  'Educational',
  'Fighting',
  'Fitness',
  'Flight',
  'Full Motion Video (FMV)',
  'Hack and Slash',
  'Hidden Object',
  'Horror',
  'Interactive Art',
  'Management',
  'Music/Rhythm',
  'Open World',
  'Party',
  'Pinball',
  'Platform',
  'Puzzle',
  'Racing/Driving',
  'Roguelike',
  'Role-Playing',
  'Sandbox',
  'Shooter',
  'Simulation',
  'Social',
  'Sports',
  'Stealth',
  'Strategy/Tactical',
  'Survival',
  'Tower Defense',
  'Trivia',
  'Vehicular Combat',
  'Visual Novel'
]
